<?php

namespace App\Enum;

enum Pathogen: string
{
    case SALMONELLA = 'SALMONELLA';
    case SHIGELLA = 'SHIGELLA';
    case YERSINIA_PESTIS = 'YERSINIA_PESTIS';
    case LISTERIA_MONOCYTOGENES = 'LISTERIA_MONOCYTOGENES';
    case VIBRIO_CHOLERAE = 'VIBRIO_CHOLERAE';
    case ENTEROHAEMORRHAGIC_ESCHERICHIA_COLI = 'ENTEROHAEMORRHAGIC_ESCHERICHIA_COLI';
}
